build: address compile issue on Fedora 42
The functions `shell_usage()` and `do_clear()` are missing a parameter:

```
glfs-cli.c:96:38: error: initialization of ‘int (*)(struct cli_context *)’ from incompatible pointer type ‘int (*)(void)’ [-Wincompatible-pointer-types]
   96 |         { .name = "help", .execute = shell_usage },
      |                                      ^~~~~~~~~~~
glfs-cli.c:96:38: note: (near initialization for ‘cmds[4].execute’)
glfs-cli.c:67:1: note: ‘shell_usage’ declared here
   67 | shell_usage ()
      | ^~~~~~~~~~~
```

Adding the (unused) `struct cli_context *` parameters to the functions
makes the compiler happy again.

Fixes: https://bugzilla.redhat.com/2340236
Signed-off-by: Niels de Vos <ndevos@ibm.com>